#!/usr/bin/env bash

MAIN_CONFIG_FILE=dtcConfig.groovy

DTC_OPTS="$DTC_OPTS -PmainConfigFile=$MAIN_CONFIG_FILE --warning-mode=none"

echo "dtcw - docToolchain wrapper V0.9"

if [[ $# -lt 1 ]]; then
    echo '
Usage: ./dtcw [option...] [task...]

You can use the same options and tasks as in underlying gradle.
Use "./dtcw tasks" to see available tasks.

Examples:

  Download and install arc42 Template:
    ./dtcw downloadTemplate

  Generate PDF:
    ./dtcw generatePDF

  Generate HTML:
    ./dtcw generateHTML

  Publish HTML to Confluence:
    ./dtcw publishToConfluence

'
    exit 1
fi

# check if CLI, docker or sdkman are installed
cli=false
docker=false
sdkman=false
homefolder=false

if command -v doctoolchain &> /dev/null; then
    echo "docToolchain as CLI available"
    cli=true
fi
if command -v docker &> /dev/null; then
    echo "docker available"
    docker=true
    if [ "$1" = "docker" ] ; then
        cli=false
        echo "force use of docker"
	shift
    fi
fi
if command -v sdk &> /dev/null; then
    echo "sdkman available"
    sdkman=true
fi
if [ -d "$HOME/.doctoolchain/." ]; then
    echo "home folder exists"
    homefolder=true
fi
if [ "$cli" = true ] ; then
    command="doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
else
    if [ "$homefolder" = true ] ; then
      command="$HOME/.doctoolchain/docToolchain-1.2.0/bin/doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
    else
      if [ "$docker" = true ] ; then
	  if ! docker info >/dev/null 2>&1; then
	      echo "Docker does not seem to be running, run it first and retry"
	      exit 1
	  fi
          docker_cmd=$(which docker)
          echo $docker_cmd
          command="$docker_cmd run --rm -it --entrypoint /bin/bash -v ${PWD}:/project rdmueller/doctoolchain:rc-1.2.0 -c \"doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 && exit\""
          echo $command
      else

          echo "docToolchain not installed."
          if [ "$sdkman" = true ] ; then
              echo "please use sdkman to install docToolchain"
              echo "$ sdk install doctoolchain 1.2.0-beta"
              exit
          else
              echo "doctoolchain not found"
              echo "Do you wish to install doctoolchain to $HOME/.doctoolchain?"
              select yn in "Yes" "No"; do
                case $yn in
                  Yes ) echo "installing doctoolchain";
                        mkdir $HOME/.doctoolchain
                        wget https://github.com/docToolchain/docToolchain/archive/v1.2.0.zip -O $HOME/.doctoolchain/source.zip
                        unzip $HOME/.doctoolchain/source.zip -d $HOME/.doctoolchain/.
                        command="$HOME/.doctoolchain/docToolchain-1.2.0/bin/doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
                        break
                    ;;
                  No )
                        echo "you need docToolchain as CLI-Tool installed or docker."
                        echo "to install docToolchain as CLI-Tool, please install"
                        echo "sdkman and re-run this command."
                        echo "https://sdkman.io/install"
                        echo "$ curl -s "https://get.sdkman.io" | bash"
                        exit 1
                    ;;
                esac
              done
          fi
       fi
    fi
fi

bash -cl "$command"
