#!/usr/bin/env bash

MAIN_CONFIG_FILE=docToolchainConfig.groovy
VERSION=ng
DISTRIBUTION_URL=https://github.com/docToolchain/docToolchain/archive/${VERSION}.zip


DTC_OPTS="$DTC_OPTS -PmainConfigFile=$MAIN_CONFIG_FILE --warning-mode=none"

echo "dtcw - docToolchain wrapper V0.12"
echo "docToolchain V${VERSION}"
if [[ $# -lt 1 ]]; then
    echo '
Usage: ./dtcw [option...] [task...]

You can use the same options and tasks as in underlying gradle.
Use "./dtcw tasks --group doctoolchain" to see available tasks.
Use "local", "sdk" or "docker" as first argument to force the use of a local, sdkman or docker install.

Examples:

  Download and install arc42 Template:
    ./dtcw downloadTemplate

  Generate PDF:
    ./dtcw generatePDF

  Generate HTML:
    ./dtcw generateHTML

  Publish HTML to Confluence:
    ./dtcw publishToConfluence
    
  get more documentation at https://doctoolchain.github.io
'
    exit 1
fi

# check if CLI, docker or sdkman are installed
cli=false
docker=false
sdkman=false
homefolder=false

if command -v java &> /dev/null; then
    java=true
else
    echo "docToolchain depends on java, but the java command couldn't be found"
    echo "to install java, one way is to install"
    echo "sdkman and then java via sdkman"
    echo "https://sdkman.io/install"
    echo "$ curl -s "https://get.sdkman.io" | bash"
    echo "$ sdk install java"
exit 1
fi

if command -v doctoolchain &> /dev/null; then
    echo "docToolchain as CLI available"
    cli=true
fi
if command -v docker &> /dev/null; then
    echo "docker available"
    docker=true
fi
if command -v sdk &> /dev/null; then
    echo "sdkman available"
    sdkman=true
fi
if [ -d "$HOME/.doctoolchain/." ]; then
    echo "home folder exists"
    homefolder=true
fi
if [ "$1" = "local" ] ; then
    echo "force use of local install"
    docker=false
    cli=false
    shift
fi
if [ "$1" = "docker" ] ; then
    cli=false
    homefolder=false
    echo "force use of docker"
    shift
fi
if [ "$1" = "sdk" ] ; then
    cli=false
    homefolder=false
    docker=false
    sdkman=true
    echo "force use of sdkman"
    shift
fi
if [ "$cli" = true ] ; then
    command="doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
    echo "use cli install $(which doctoolchain)"
else
    if [ "$homefolder" = true ] ; then
      command="$HOME/.doctoolchain/docToolchain-${VERSION}/bin/doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
      echo "use local homefolder install $HOME/.doctoolchain/"
    else
      if [ "$docker" = true ] ; then
	  if ! docker info >/dev/null 2>&1; then
	      echo "Docker does not seem to be running, run it first and retry"
	      exit 1
	  fi
          docker_cmd=$(which docker)
          echo $docker_cmd
          command="$docker_cmd run --rm -it --entrypoint /bin/bash -v ${PWD}:/project rdmueller/doctoolchain:${VERSION} -c \"doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS && exit\""
          echo "use docker installation"
      else

          echo "docToolchain not installed."
          if [ "$sdkman" = true ] ; then
              echo "please use sdkman to install docToolchain"
              echo "$ sdk install doctoolchain ${VERSION}-beta"
              exit
          else
              echo "doctoolchain not found"
              echo "Do you wish to install doctoolchain to $HOME/.doctoolchain?"
              select yn in "Yes" "No"; do
                case $yn in
                  Yes ) echo "installing doctoolchain";
                        mkdir $HOME/.doctoolchain
                        wget $DISTRIBUTION_URL -O $HOME/.doctoolchain/source.zip
                        unzip $HOME/.doctoolchain/source.zip -d $HOME/.doctoolchain/.
                        command="$HOME/.doctoolchain/docToolchain-${VERSION}/bin/doctoolchain . $1 $2 $3 $4 $5 $6 $7 $8 $9 $DTC_OPTS"
                        break
                    ;;
                  No )
                        echo "you need docToolchain as CLI-Tool installed or docker."
                        echo "to install docToolchain as CLI-Tool, please install"
                        echo "sdkman and re-run this command."
                        echo "https://sdkman.io/install"
                        echo "$ curl -s "https://get.sdkman.io" | bash"
                        exit 1
                    ;;
                esac
              done
          fi
       fi
    fi
fi

bash -cl "$command"
