# This is a basic workflow to help you get started with Actions

name: update-dtcw

# Controls when the workflow will run
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: publish-dtcw
        run: |

          git config --global user.email "github-action@docs-as-co.de"
          git config --global user.name "github-action"
          
          echo "GITHUB_ACTOR = ${GITHUB_ACTOR}"
          git clone https://github.com/docToolchain/doctoolchain
          
          cp doctoolchain/dtcw     dtcw
          cp doctoolchain/dtcw.ps1 dtcw.ps1
          cp doctoolchain/dtcw.bat dtcw.bat
          cat doctoolchain/dtcw.ps1 >> dtcw.bat
          
          rm -r doctoolchain
          
          git add .
          git commit -m "new update of dtcw"
          git push
          
